<?php 
Redux::setSection( $opt_name, array(
    'title'            => __( 'Sliders Default', 'feellio' ),
    'id'               => 'wd_slider',
    'desc'             => __( 'Customize default arguments for slider (Owl Carousel).', 'feellio' ),
    'customizer_width' => '400px',
    'icon'             => 'el el-fast-forward',
    'fields'     => array(
        array(
            'id'       => 'wd_slider_column_desktop',
            'type'     => 'button_set',
            'title'    => __( 'Column On Desktop', 'feellio' ),
            'desc'     => '',
            'options'  => $wd_default_data['columns']['choose']['desktop'],
            'default'  => $wd_default_data['slider']['default']['column_desktop'], 
        ),
        array(
            'id'       => 'wd_slider_column_tablet',
            'type'     => 'button_set',
            'title'    => __( 'Column On Tablet', 'feellio' ),
            'desc'     => '',
            'options'  => $wd_default_data['columns']['choose']['tablet'],
            'default'  => $wd_default_data['slider']['default']['column_tablet'], 
        ),
        array(
            'id'       => 'wd_slider_column_mobile',
            'type'     => 'button_set',
            'title'    => __( 'Column On Mobile', 'feellio' ),
            'desc'     => '',
            'options'  => $wd_default_data['columns']['choose']['mobile'],
            'default'  => $wd_default_data['slider']['default']['column_mobile'], 
        ),
        array(
            'id'       => 'wd_slider_autoplay',
            'type'     => 'switch',
            'title'    => __( 'Autoplay', 'feellio' ),
            'subtitle' => '',
            'default'  => $wd_default_data['slider']['default']['autoplay'],
            'on'       => 'Enable',
            'off'      => 'Disable',
        ),
        array(
            'id'       => 'wd_slider_autoplay_setting_section_start',
             'type'     => 'section',
             'title'    => __( 'Autoplay Settings', 'feellio' ),
             'subtitle' => '',
             'indent'   => true,
            'required' => array('wd_slider_autoplay','=', true ),
        ),
        /****************************/
            array(
                'id'       => 'wd_slider_autoplay_hover_pause',
                'type'     => 'switch',
                'title'    => __( 'Autoplay Hover Pause', 'feellio' ),
                'subtitle' => '',
                'default'  => $wd_default_data['slider']['default']['autoplayHoverPause'],
                'on'       => 'Show',
                'off'      => 'Hide',
                'required' => array('wd_slider_autoplay', '=', true),
            ),
            array(
                'id'       => 'wd_slider_autoplay_speed',
                'type'     => 'text',
                'title'    => __( 'Autoplay Speed (Unit: ms)', 'feellio' ),
                'subtitle' => '',
                'desc'     => '',
                'default'  => $wd_default_data['slider']['default']['autoplaySpeed'],
                'required' => array('wd_slider_autoplay', '=', true),
            ),
            array(
                'id'       => 'wd_slider_autoplay_timeout',
                'type'     => 'text',
                'title'    => __( 'Autoplay Time Out (Unit: ms)', 'feellio' ),
                'subtitle' => '',
                'desc'     => '',
                'default'  => $wd_default_data['slider']['default']['autoplayTimeout'],
                'required' => array('wd_slider_autoplay', '=', true),
            ),
        /****************************/
        array(
            'id'     => 'wd_slider_autoplay_setting_section_end',
            'type'   => 'section',
            'indent' => false,
            'required' => array('wd_slider_autoplay','=', true ),
        ),
        array(
            'id'       => 'wd_slider_autoplay_mobile',
            'type'     => 'switch',
            'title'    => __( 'Autoplay Mobile', 'feellio' ),
            'subtitle' => '',
            'default'  => $wd_default_data['slider']['default']['autoplay_mobile'],
            'on'       => 'Enable',
            'off'      => 'Disable',
        ),
        array(
            'id'       => 'wd_slider_arrows',
            'type'     => 'switch',
            'title'    => __( 'Arrows', 'feellio' ),
            'subtitle' => '',
            'default'  => $wd_default_data['slider']['default']['arrows'],
            'on'       => 'Show',
            'off'      => 'Hide',
        ),
        array(
            'id'       => 'wd_slider_dots',
            'type'     => 'switch',
            'title'    => __( 'Dots', 'feellio' ),
            'subtitle' => '',
            'default'  => $wd_default_data['slider']['default']['dots'],
            'on'       => 'Show',
            'off'      => 'Hide',
        ),
        array(
            'id'       => 'wd_slider_infinite',
            'type'     => 'switch',
            'title'    => __( 'Infinite', 'feellio' ),
            'subtitle' => '',
            'default'  => $wd_default_data['slider']['default']['infinite'],
            'on'       => 'Enable',
            'off'      => 'Disable',
        ),
        array(
            'id'       => 'wd_slider_responsive_refresh_rate',
            'type'     => 'text',
            'title'    => __( 'Responsive Refresh Rate (Unit: ms)', 'feellio' ),
            'subtitle' => '',
            'desc'     => '',
            'default'  => $wd_default_data['slider']['default']['responsiveRefreshRate'],
            'required' => array('wd_slider_autoplay', '=', true),
        ),
        array(
            'id'       => 'wd_slider_nav_rewind',
            'type'     => 'switch',
            'title'    => __( 'Nav Rewind', 'feellio' ),
            'subtitle' => '',
            'default'  => $wd_default_data['slider']['default']['navRewind'],
            'on'       => 'Enable',
            'off'      => 'Disable',
        ),
        array(
            'id'       => 'wd_slider_nav_speed',
            'type'     => 'text',
            'title'    => __( 'Nav Speed (Unit: ms)', 'feellio' ),
            'subtitle' => '',
            'desc'     => '',
            'default'  => $wd_default_data['slider']['default']['navSpeed'],
        ),
        array(
            'id'       => 'wd_slider_margin',
            'type'     => 'text',
            'title'    => __( 'Margin (Unit: pixel)', 'feellio' ),
            'subtitle' => '',
            'desc'     => '',
            'default'  => $wd_default_data['slider']['default']['margin'],
        ),
        array(
            'id'       => 'wd_slider_auto_height',
            'type'     => 'switch',
            'title'    => __( 'Auto Height', 'feellio' ),
            'subtitle' => '',
            'default'  => $wd_default_data['slider']['default']['autoHeight'],
            'on'       => 'Enable',
            'off'      => 'Disable',
        ),
        array(
            'id'       => 'wd_slider_mouse_drag',
            'type'     => 'switch',
            'title'    => __( 'Mouse Drag', 'feellio' ),
            'subtitle' => '',
            'default'  => $wd_default_data['slider']['default']['mouseDrag'],
            'on'       => 'Enable',
            'off'      => 'Disable',
        ),
        array(
            'id'       => 'wd_slider_touch_drag',
            'type'     => 'switch',
            'title'    => __( 'Touch Drag', 'feellio' ),
            'subtitle' => '',
            'default'  => $wd_default_data['slider']['default']['touchDrag'],
            'on'       => 'Enable',
            'off'      => 'Disable',
        ),
        array(
            'id'       => 'wd_slider_animate_in',
            'type'     => 'text',
            'title'    => __( 'Animate In', 'feellio' ),
            'subtitle' => __( 'This effect is only activated on single column layout.', 'feellio' ),
            'desc'     => sprintf(__( '<a href="%s" target="_blank">View all animations</a>', 'feellio' ), esc_url('https://daneden.github.io/animate.css/')),
            'default'  => $wd_default_data['slider']['default']['animateIn'],
        ),
        array(
            'id'       => 'wd_slider_animate_out',
            'type'     => 'text',
            'title'    => __( 'Animate Out', 'feellio' ),
            'subtitle' => __( 'This effect is only activated on single column layout.', 'feellio' ),
            'desc'     => sprintf(__( '<a href="%s" target="_blank">View all animations</a>', 'feellio' ), esc_url('https://daneden.github.io/animate.css/')),
            'default'  => $wd_default_data['slider']['default']['animateOut'],
        ),
    )
) );
Redux::setSection( $opt_name, array(
    'title'            => __( 'Slider Settings', 'ifind' ),
    'id'               => 'ifind_time_settings',
    'desc'             => __( '', 'ifind' ),
    'icon'             => 'el el-time',
    'customizer_width' => '400px',
    'fields'     => array(
        array(
            'id'       => 'ifind_slider_timerShowPopup',
            'type'     => 'text',
            'title'    => __( 'Show Popup After', 'ifind' ),
            'subtitle' => __( 'Waiting time before show large popup slider.', 'ifind' ),
            'desc'     => __( 'Unit: ms (1000ms = 1s)', 'ifind' ),
            'default'  => $wd_default_data['slider']['default']['timerShowPopup'],
        ),
        array(
            'id'       => 'ifind_slider_timerShowPopupViewingInfo',
            'type'     => 'text',
            'title'    => __( 'Show Popup After (When watching information)', 'ifind' ),
            'subtitle' => __( 'Waiting time before show large popup slider.', 'ifind' ),
            'desc'     => __( 'Unit: ms (1000ms = 1s)', 'ifind' ),
            'default'  => $wd_default_data['slider']['default']['timerShowPopupViewingInfo'],
        ),
        array(
            'id'       => 'ifind_slider_timerDelayPopup',
            'type'     => 'text',
            'title'    => __( 'Popup Delay', 'ifind' ),
            'subtitle' => __( 'Time delay after slider break.', 'ifind' ),
            'desc'     => __( 'Unit: ms (1000ms = 1s)', 'ifind' ),
            'default'  => $wd_default_data['slider']['default']['timerDelayPopup'],
        ),
        array(
            'id'       => 'ifind_slider_numSliderBreak',
            'type'     => 'text',
            'title'    => __( 'Break Popup Slider After Item', 'ifind' ),
            'subtitle' => __( 'Slider will break after number slide.', 'ifind' ),
            'desc'     => __( '', 'ifind' ),
            'default'  => $wd_default_data['slider']['default']['numSliderBreak'],
        ),
        array(
            'id'       => 'ifind_slider_bigAutoplaySpeed',
            'type'     => 'text',
            'title'    => __( 'Popup Slider Autoplay Speed', 'ifind' ),
            'subtitle' => __( '', 'ifind' ),
            'desc'     => __( 'Unit: ms (1000ms = 1s)', 'ifind' ),
            'default'  => $wd_default_data['slider']['default']['bigAutoplaySpeed'],
        ),
        array(
            'id'       => 'ifind_slider_smallAutoplaySpeed',
            'type'     => 'text',
            'title'    => __( 'Top Slider Autoplay Speed', 'ifind' ),
            'subtitle' => __( '', 'ifind' ),
            'desc'     => __( 'Unit: ms (1000ms = 1s)', 'ifind' ),
            'default'  => $wd_default_data['slider']['default']['smallAutoplaySpeed'],
        ),
        array(
            'id'       => 'ifind_slider_numFooterSliderItems',
            'type'     => 'text',
            'title'    => __( 'Footer Slider Items', 'ifind' ),
            'subtitle' => __( 'Slide number of footer slider.', 'ifind' ),
            'desc'     => __( '', 'ifind' ),
            'default'  => $wd_default_data['slider']['default']['numFooterSliderItems'],
        ),
    ) 
) );